### ISSUE TITLE
New version breaks compatibility with non-dask data

### ISSUE THREAD

**Issue by stephenpardy** [dask/dask-glm#104]
**Describe the issue**:

Version 0.3.0 includes changes that break the compatibility of some functions - notably the families - to work with non-dask data. 

As one example, the [newton](https://github.com/dask/dask-glm/blob/5194d6f709878cbcbdc4eed6852c3c35a5d3357a/dask_glm/algorithms.py#L170) function changed the line calculating betas from:
```
beta = np.zeros_like(X, shape=p)
```

to:
```
beta = np.zeros_like(X._meta, shape=p)
```

which will fail for any non-dask data. 

**Minimal Complete Verifiable Example**:

```python
from dask_glm.algorithms import newton
import numpy as np
X = np.random.random((100, 3))
y = np.random.random((100,))
newton(X, y)
```

**Anything else we need to know?**: If this is an intended change, would be good to call out the reason for it (sorry if I missed it). 

**Environment**: Local (macbook pro - M1)

- Dask version: `2023.3.0`
- Python version: 3.10.10
- Operating System: Mac osx
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
Thanks @stephenpardy !  We'll take a look.  As a heads-up tomorrow is a national holiday in Germany (where some of the folks that are likely to work on this are located) so we may be slow to respond until Thursday.

**Comment by milesgranger** [comment]
Git bisect'd to #87, will address from here.
