### ISSUE TITLE
Add default arguments to ADMM code

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-glm#16]
I started trying to play with @hussainsultan 's ADMM code.  However, it requires many parameters for which I do not know good values.  Can we add sane defaults there?  Do we know sane defaults?

Short term it would be useful to me to always be able to do the following for all solver routines:

    result = func(X, y)

**Comment by hussainsultan** [comment]
Thanks for the call out. Thats sometime that i intended to clean in my initial PR but then got sidetracked by consolidation. I will take this on.

**Comment by moody-marlin** [comment]
This should be resolved in PR #22

**Comment by hussainsultan** [comment]
resolved by #22. closing
