### ISSUE TITLE
create conda-forge package

### ISSUE THREAD

**Issue by hussainsultan** [dask/dask-glm#33]
For running `dask-glm` in  internal (enterprise) environment,  i run into scenarios where a conda-forge package is much easier to mirror internally than straight from the git (external) repo.

**Comment by mrocklin** [comment]
Seems like a good idea.  This is easier if there is a PyPI package.  @moody-marlin any objection to my tagging a release and pushing this project to PyPI with a heavy disclaimer?

**Comment by moody-marlin** [comment]
No strong objections; maybe we can wait until tomorrow to see if / what we add to dask-glm in the next 24 hours?  Otherwise I'm fine with it.

**Comment by jrbourbeau** [comment]
Closing as `dask-glm` is available on conda-forge now (see https://github.com/conda-forge/dask-glm-feedstock)
