### ISSUE TITLE
Merge forks/branches

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-glm#4]
People have submitted PRs to three forks/branches recently:

1.  dask/master
2.  moody-marlin/master
3.  moody-marlin/no_api

It would be good to merge these all to some fork/branch quickly so that we don't need to go through expensive merging later on.  I don't particulaly care which fork/branch, but I would prefer to see things drive towards a common point.  It becomes expensive to merge if things diverge for too long.

cc @moody-marlin @hussainsultan

**Comment by hussainsultan** [comment]
Thanks for the callout. I am working with @moody-marlin to consolidate all the previous work and make a PR to dask-glm repo. Going forward, `dask/dask-glm` should be the only repo that we work with instead of working with forks directly. Thoughts?

**Comment by mrocklin** [comment]
I'm personally fine with anything, as long as code doesn't linger too long
in other forks/branches.  I personally tend to develop within my own fork
and then merge within a few days.
