### ISSUE TITLE
Add conda environment.yml

### ISSUE THREAD

**Issue by hussainsultan** [dask/dask-glm#6]
@moody-marlin pointed out that we need to add an environment.yml file for ease of use with conda.

**Comment by hussainsultan** [comment]
@mrocklin  do you know if a single `environment.yml` file could work for both python2 and 3? I am reading up the docs and couldn't find this on first pass.

**Comment by mrocklin** [comment]
I have to admit that I never use conda environment.yml files

**Comment by moody-marlin** [comment]
Closed with #29.
