### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-glm#99]
It appears this is currently unmaintained. If that is the case, should we go ahead and archive this repo?

**Comment by jakirkham** [comment]
cc @cicdw @TomAugspurger

**Comment by TomAugspurger** [comment]
+1On Dec 6, 2022, at 4:49 PM, jakirkham ***@***.***> wrote:﻿
cc @cicdw @TomAugspurger

**Comment by fjetter** [comment]
FYI There is some interest in reviving this repo and we will invest some time to get this up and running again

**Comment by TomAugspurger** [comment]
The source lives at https://github.com/dask/dask-ml/blob/main/dask_ml/linear_model/glm.py and related files now. Or is there some other reason to revive it?
